name: "Build @propfull/kit library"

on:
  pull_request:
    branches:
      - latest

env:
  NODE_VERSION: "12.8.0"
  ARTEFACT_DIRECTORY: dist

jobs:
  build_library:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build project
        run: pnpm run build

      - name: Upload library artefact
        uses: actions/upload-artifact@v1
        with:
          name: kit
          path: ${{ env.ARTEFACT_DIRECTORY }}
