name: "Deploy @propfull/kit package to NPM Registry"

on:
  push:
    branches:
      - cool

env:
  NODE_VERSION: "12.8.0"
  ARTEFACT_DIRECTORY: dist

jobs:
  deploy_package:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          scope: '@propfull'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build project
        run: pnpm run build

      - name: Upload library artefact
        uses: actions/upload-artifact@v1
        with:
          name: kit
          path: ${{ env.ARTEFACT_DIRECTORY }}

      - name: write npmrc
        run: |
          echo 'registry="https://registry.npmjs.org" 
          //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc

      - name: Deploy to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN_FOR_NPM }}
